#ifndef FFPLAYCPPDLL_GLOBAL_H
#define FFPLAYCPPDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FFPLAYCPPDLL_LIBRARY)
#  define FFPLAYCPPDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FFPLAYCPPDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FFPLAYCPPDLL_GLOBAL_H
